---

- name: Backend Configuration
  hosts: backend
  become: yes
  tasks:
    - name: 01 - Disabling Nodejs Package
      ansible.builtin.command: dnf module disable nodejs -y
    - name: 02 - Enabling Nodejs version 20 Package
      ansible.builtin.command: dnf module enable nodejs:20 -y
    - name: 03 - Installing Nodejs and Mysql Package
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - mysql
    - name: 04 - Creating an user
      ansible.builtin.user:
        name: expense
    - name: 05 - Creating a app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: 06 - Downloading the backend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip
    - name: 07 - Unzipping the backend code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes
    - name: 08 - Installing the npm dependencies
      community.general.npm:
        path: /app
    - name: 09 - Copying BackendService to service
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/BackendService.service
    - name: 10 - copying the db script file to mysql
      community.mysql.mysql_db:
        state: import
        name: all 
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql.siliconapps.in
        target: /app/schema/backend.sql