---

- name: Backend Configuration
  hosts: backend
  become: yes
  tasks:
    - name: 01 - Disabling Nodejs Package
      ansible.builtin.command: dnf module disable nodejs -y
    - name: 02 - Enabling Nodejs version 20 Package
      ansible.builtin.command: dnf module enable nodejs:20 -y
    - name: 03 - Installing Nodejs Package
      ansible.builtin.package:
        name: nodejs
        state: present
    - name: 04 - Creating an user
      ansible.builtin.user:
        name: expense
    - name: 05 - Creating a app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: 06 - Downloading the backend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip
    - name: 07 - Unzipping the backend code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app