---

- name: configur frontend Server
  hosts: frontend
  become: yes
  tasks:
    - name: 01 -  install nginix
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: 02 -  start nginix
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: 03 - create a html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: 04 - download the frontend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip

    - name: 05 - unzip the frontend code
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes