---

- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql libraries
    absible.builtin.pip:
      name: PyMySQL
      executable: pip3.9
      
  - name: 01 - Install MYSQL Server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: 02 - Start & Enable MYSQL Server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
  - name: 03 - connect to mysql-server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.siliconapps.in
    register: mysql_info

  - name: 04 - print the output
    ansible.builtin.debug:
      var: "{{ mysql_info }}"